POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlNyaWxla2hhQGtpbmcuY29tIiwiZXhwIjoxNzgwMTcwNzA3LCJ1c2VySWQiOjJ9.4rXu0Ot-XsLnDkzGnLhCGDV14cYhqB2lRzo2HapA4cU

{
    "name" : "Test Event4",
    "description" : "Test Description",
    "location" : "Chennai",
    "dateTime" : "2025-01-21T15:30:35.000Z"
}