PUT http://localhost:8080/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlNyaWxla2hhQGtpbmcuY29tIiwiZXhwIjoxNzgwMTcxMDEzLCJ1c2VySWQiOjJ9.L-qsjqeyhGyAwGfRnq9kKt6s5JMjc0P0N_M92G3VMIM

{
    "name" : "UpdateEvent",
    "description" : "Update Description",
    "location" : "Rajahmundry",
    "dateTime" : "2026-02-04T16:54:53.000Z"
}