PUT http://localhost:8080/events/3
Content-Type: application/json

{
    "name" : "UpdateEvent",
    "description" : "Update Description",
    "location" : "Rajahmundry",
    "dateTime" : "2026-02-04T16:54:53.000Z"
}